// Datos de productos — fuente de verdad local
// Cuando Supabase esté configurado, la API /api/productos los sirve desde la DB.
// Esta lista se usa como fallback y en los componentes Server Side.

import type { Producto } from "./types";

export const PRODUCTOS: Producto[] = [
  {
    id: 1,
    marca: "reebook",
    nombre: "Energen Run 3",
    descripcion: "Modelo comodo para uso diario, caminatas activas y entrenamiento suave.",
    precio: 80000,
    deporte: "running",
    tag: "Amortiguacion diaria",
    badge: "Running",
    imagenes: ["/img/producto1,1.jpeg", "/img/producto1,2.jpeg", "/img/producto1,3.jpeg"],
    talles: [38.5, 39.5, 40, 41, 41.5, 42, 43, 45, 45.5],
    tallesNota: "",
    colores: [{ nombre: "Gris", hex: "#9CA3AF" }, { nombre: "Negro", hex: "#111111" }],
    activo: true,
  },
  {
    id: 2,
    marca: "reebook",
    nombre: "Energen Lite JP",
    descripcion: "Una opcion agil y versatil para quienes buscan comodidad sin exceso de peso.",
    precio: 65000,
    deporte: "running",
    tag: "Liviana",
    badge: "Running",
    imagenes: ["/img/producto2,1.jpeg", "/img/producto2,2.jpeg"],
    talles: [35, 36, 37, 39, 40, 41, 42, 43, 44],
    tallesNota: "",
    colores: [{ nombre: "Blanco", hex: "#FFFFFF" }, { nombre: "Azul", hex: "#3B82F6" }],
    activo: true,
  },
  {
    id: 3,
    marca: "olympikus",
    nombre: "Plaza Running",
    descripcion: "Diseno noble y estable para quienes priorizan comodidad y apoyo parejo.",
    precio: 80000,
    deporte: "running",
    tag: "Uso diario",
    badge: "Respuesta suave",
    imagenes: ["/img/producto3,1.jpeg", "/img/producto3,2.jpeg"],
    talles: [36, 37, 38, 39, 40, 41],
    tallesNota: "",
    colores: [{ nombre: "Azul marino", hex: "#1E3A5F" }, { nombre: "Verde", hex: "#10B981" }],
    activo: true,
  },
  {
    id: 4,
    marca: "topper",
    nombre: "Wind 5 Running",
    descripcion: "Una silueta deportiva, firme y rendidora para ritmo cotidiano.",
    precio: 79000,
    deporte: "running",
    tag: "Rendimiento urbano",
    badge: "Precio fuerte",
    imagenes: ["/img/producto4,1.jpeg", "/img/producto4,2.jpeg", "/img/producto4,3.jpeg"],
    talles: [38, 39, 40, 41, 42, 43, 44, 45],
    tallesNota: "",
    colores: [{ nombre: "Negro", hex: "#111111" }, { nombre: "Blanco", hex: "#FFFFFF" }],
    activo: true,
  },
  {
    id: 5,
    marca: "topper",
    nombre: "Suva",
    descripcion: "Excelente opcion para arrancar con un modelo funcional y rendidor.",
    precio: 60000,
    deporte: "running",
    tag: "Precio accesible",
    badge: "Entrada ideal",
    imagenes: ["/img/producto5,1.jpeg"],
    talles: [37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    tallesNota: "",
    colores: [{ nombre: "Rojo", hex: "#EF4444" }, { nombre: "Negro", hex: "#111111" }],
    activo: true,
  },
  {
    id: 6,
    marca: "atomik",
    nombre: "Fairfaxx",
    descripcion: "Modelo liviano con pocas unidades disponibles en cada talle.",
    precio: 65000,
    deporte: "running",
    tag: "Stock limitado",
    badge: "Ultimas unidades",
    imagenes: [
      "/img/producto6,1.jpeg",
      "/img/producto6,2.jpeg",
      "/img/producto6,3.jpeg",
      "/img/producto6,4.jpeg",
    ],
    talles: [35, 36, 39, 41, 42, 43, 44, 45],
    tallesNota: "(1 unidad c/u)",
    colores: [{ nombre: "Gris", hex: "#6B7280" }, { nombre: "Naranja", hex: "#F97316" }],
    activo: true,
  },
];
